use_frameworks!

platform :ios, '11.0'

target 'IGEX_Example' do
  pod 'IGEX', :path => '../'

  target 'IGEX_Tests' do
    inherit! :search_paths

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxGesture'
    pod 'IGListKit'
    pod 'Core', git: 'https://github.com/syquandev/Core'
    
  end
end
